name: 'Run hottest'
description: 'Run hottest command with user-specified arguments'
author: "Naohiro CHIKAMATSU <n.chika156@gmail.com>"
inputs:
  args:
    description: 'Arguments to pass to hottest command'
    required: true
runs:
  using: 'composite'
  steps:
    - run: bash $GITHUB_ACTION_PATH/entrypoint.sh ${{ inputs.args }}
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}
