name: 'Run hottest'
description: 'Run hottest command with user-specified arguments'
author: "Naohiro CHIKAMATSU <n.chika156@gmail.com>"
inputs:
  args:
    description: 'Arguments to pass to hottest command'
    required: true
runs:
  using: 'composite'
  steps:
    - run: bash $GITHUB_ACTION_PATH/entrypoint.sh ${{ inputs.args }}
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}

    - name: Find existing comment
      id: find_comment
      uses: peter-evans/find-comment@v2
      with:
        issue-number: ${{ github.event.number }}
        body-includes: "## HOTTEST report"

    - name: Delete existing comment
      shell: bash
      if: steps.find_comment.outputs.comment-id
      run: |
        curl \
          -X DELETE \
          -H "Authorization: token $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github+json" \
          "https://api.github.com/repos/${{ github.repository }}/issues/comments/${{ steps.find_comment.outputs.comment-id }}"

    - name: Comment coverage on PR
      uses: peter-evans/create-or-update-comment@v3
      with:
        token: $GITHUB_TOKEN
        issue-number: ${{ github.event.number }}
        body-path: 'hottest_report.md'