name: 'Run hottest'
description: 'Run hottest command with user-specified arguments'
author: "Naohiro CHIKAMATSU <n.chika156@gmail.com>"
inputs:
  args:
    description: 'Arguments to pass to hottest command'
    required: true
runs:
  using: 'composite'
  steps:
    - name: 'Install hottest'
      uses: 'shell'
      run: go install github.com/nao1215/hottest@latest
    - name: 'Run hottest'
      uses: 'shell'
      run: hottest ${{ inputs.args }}
