name: Run Custom Hottest Action

on:
  push:

jobs:
  run_hottest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run Custom Hottest Action
        uses: ./
        with:
          args: ''